version: "3"

services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    command: v2ray -config=/etc/v2ray/config.json
    ports:
      - "127.0.0.1:10808:10808"
      - "127.0.0.1:8128:8128"
    volumes:
      - "${HOME}/.settings/v2ray.json:/etc/v2ray/config.json"

